Fix TypeError issue
Without casting my_prediction as an integer it throws an error.

TypeError: only integer scalar arrays can be converted to a scalar index